version: '3.8'

services:
  model-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: projet_fil_rouge_api-model-api-1
    environment:
    - HOME=/tmp
    - HF_HOME=/tmp/.cache/huggingface
    - TRANSFORMERS_CACHE=/tmp/.cache/huggingface/transformers
    - SENTENCE_TRANSFORMERS_HOME=/tmp/.cache/torch/sentence_transformers
    ports:
      - "9500:8000"
    env_file:
      - .env 
    restart: unless-stopped
